[project]
name = "src"
version = "0.1.0"

dependencies = [
	"pytest==8.4.2",
	"staticfg==0.9.5",
	"pytest-cov==7.0.0",
]

[tool.mutmut]
paths_to_mutate = "src/energy/EnergyManagementResult.py,src/flight/FlightBookingSystem.py,src/fraud/FraudDetectionSystem.py"

[tool.setuptools]
packages = ["src"]